### PR TITLE
Adding scripts for cl_papers.csv and tacl_papes.csv

### PR DESCRIPTION
**Pull request by shruti-singh**
Adding scripts for generating cl_papers.csv, tacl_papers.csv, cl_paper_sessions.yml and tacl_paper_sessions.yml
Files PR: https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/78

### CODE REVIEW

**Comment by hao-fang** [comment]
@shruti-singh Can you run `make format` locally to fix the the Github Action errors?

**Comment by shruti-singh** [comment]
> @shruti-singh Can you run `make format` locally to fix the the Github Action errors?

I am really sorry for the to and fro. I have fixed the errors and squashed all the commits into one commit. Thanks!

**Comment by hao-fang** [comment]
@shruti-singh No problem at all! This is a common issue which should have added to the CONTRIBUTION.ACL2020.md.
Thanks for making the changes!

**Review by hao-fang — APPROVED** [review]
Thanks a lot!

**Pull request merged**
